-- [ Basic SELECT ] --
-- 1.
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열
FROM TB_DEPARTMENT;

--2. x
SELECT 

--3.
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
AND SUBSTR(STUDENT_SSN, 8, 1) = '2'
AND ABSENCE_YN = 'Y';

--4. x
SELECT STUDENT_NAME
FROM TB_STUDENT


--5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6. 
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


--7. x
SELECT STUDENT_NAME
FROM TB_STUDENT

--8.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9.
SELECT CATEGORY FROM TB_DEPARTMENT
UNION
SELECT CATEGORY FROM TB_DEPARTMENT;

--10. 
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE,ABSENCE_YN 
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE, 2, 1)='2'
AND STUDENT_ADDRESS LIKE '%전주%'
AND ABSENCE_YN ='N';


-- [ Additional SELECT - 함수 ] --
-- 1. 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, 
		TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 1;

--2. x
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PRORESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';


-- 3. x 나이 계산해야함
SELECT PROFESSOR_NAME 교수이름, 

--4.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSO, 1, 2);









